version: '3.8'
services:
  warehouse-db:
    image: postgres:16.0
    container_name: warehouse-db
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: thanh1203
      POSGRES_DB: warehousedb